### ISSUE TITLE
Consider handling ClasspathResources as BrowsableResources

### ISSUE THREAD

**Issue by may-bee** [m-m-m/mmm#135]
It might be interesting to also browse through libraries included in the classpath as supported by Java NIO ZipProvider. This also includes listing resources of a directory.

As this might be very resources consuming, a good caching mechanism has to be implemented. First we should perform feasibility analyses to gain some more information.

**Comment by hohwille** [comment]
Thanks for the suggestion. I will implement this soon but have no time for ~2 weeks...

**Comment by hohwille** [comment]
Commit accidentally had wrong format and was not associated with this issue:
https://github.com/m-m-m/mmm/commit/20869f9275f757ecede99a2a06bdf65231dfe8c2

**Comment by hohwille** [comment]
So we did not change ClasspathResource but instead add ClasspathScanner as a "component" that allows to retrive BrowsableResource instances to browse the classpath just like a filesystem.

**Comment by hohwille** [comment]
Done:
https://github.com/m-m-m/mmm/blob/master/mmm-util/mmm-util-core/src/test/java/net/sf/mmm/util/resource/base/ClasspathScannerTest.java

**Comment by may-bee** [comment]
:+1: Thanks!
You should start writing a blog to publish your work a little bit more :)
